name: overmind # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.0.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Process manager for Procfile-based applications
description: |
  Overmind is a process manager for Procfile-based applications and tmux.
  With Overmind, you can easily run several processes from your Procfile in a single terminal.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    plugin: go
    go-importpath: github.com/DarthSim/overmind/v2
    source: .
    source-type: git
